import type { ProductVerticalDefinition } from "./types";

const laptopOnly = {
  key: "electronics-type",
  values: ["laptop"],
} as const;

const accessoryOnly = {
  key: "electronics-type",
  values: ["accessory"],
} as const;

const yesNoOptions = [
  { value: "true", label: "نعم" },
  { value: "false", label: "لا" },
] as const;

export const electronicsVertical: ProductVerticalDefinition = {
  code: "electronics",

  label: "لابتوبات وإكسسوارات",
  badgeLabel: "إلكترونيات",

  description:
    "منتجات إلكترونية متخصصة. اختر لابتوب أو إكسسوار لتظهر المواصفات المناسبة فقط.",

  fields: [
    {
      key: "electronics-type",
      label: "نوع المنتج الإلكتروني",
      type: "select",
      group: "identity",
      required: true,
      options: [
        { value: "laptop", label: "لابتوب" },
        { value: "accessory", label: "إكسسوار" },
      ],
    },
    {
      key: "brand",
      label: "العلامة التجارية",
      type: "text",
      group: "identity",
      placeholder: "Apple / ASUS / Lenovo / Anker...",
    },
    {
      key: "model",
      label: "الموديل",
      type: "text",
      group: "identity",
    },
    {
      key: "release-year",
      label: "سنة الإصدار",
      type: "number",
      group: "details",
    },
    {
      key: "condition",
      label: "حالة المنتج",
      type: "select",
      group: "details",
      options: [
        { value: "new", label: "جديد" },
        { value: "used", label: "مستعمل" },
        { value: "refurbished", label: "مجدد" },
      ],
    },
    {
      key: "processor-brand",
      label: "شركة المعالج",
      type: "select",
      group: "performance",
      visibleWhen: laptopOnly,
      options: [
        { value: "intel", label: "Intel" },
        { value: "amd", label: "AMD" },
        { value: "apple", label: "Apple" },
        { value: "qualcomm", label: "Qualcomm" },
        { value: "other", label: "أخرى" },
      ],
    },
    {
      key: "processor-model",
      label: "المعالج",
      type: "text",
      group: "performance",
      visibleWhen: laptopOnly,
      placeholder: "Core Ultra 7 / Ryzen 7 / M4...",
    },
    {
      key: "processor-generation",
      label: "جيل المعالج",
      type: "text",
      group: "performance",
      visibleWhen: laptopOnly,
    },
    {
      key: "cpu-cores",
      label: "عدد الأنوية",
      type: "number",
      group: "performance",
      visibleWhen: laptopOnly,
    },
    {
      key: "gpu-model",
      label: "كرت الشاشة",
      type: "text",
      group: "performance",
      visibleWhen: laptopOnly,
      placeholder: "RTX 5070 / Radeon / Apple GPU...",
    },
    {
      key: "gpu-type",
      label: "نوع كرت الشاشة",
      type: "select",
      group: "performance",
      visibleWhen: laptopOnly,
      options: [
        { value: "integrated", label: "مدمج" },
        { value: "dedicated", label: "منفصل" },
      ],
    },
    {
      key: "vram-gb",
      label: "ذاكرة كرت الشاشة VRAM",
      type: "number",
      group: "performance",
      visibleWhen: laptopOnly,
      helpText: "بالجيجابايت.",
    },
    {
      key: "ram-gb",
      label: "RAM",
      type: "number",
      group: "performance",
      visibleWhen: laptopOnly,
      helpText: "بالجيجابايت.",
    },
    {
      key: "ram-type",
      label: "نوع RAM",
      type: "text",
      group: "performance",
      visibleWhen: laptopOnly,
      placeholder: "DDR5 / LPDDR5X...",
    },
    {
      key: "ram-speed-mhz",
      label: "سرعة RAM",
      type: "number",
      group: "performance",
      visibleWhen: laptopOnly,
      helpText: "MHz",
    },
    {
      key: "storage-gb",
      label: "مساحة التخزين",
      type: "number",
      group: "performance",
      visibleWhen: laptopOnly,
      helpText: "بالجيجابايت.",
    },
    {
      key: "storage-type",
      label: "نوع التخزين",
      type: "select",
      group: "performance",
      visibleWhen: laptopOnly,
      options: [
        { value: "nvme", label: "NVMe" },
        { value: "ssd", label: "SSD" },
        { value: "hdd", label: "HDD" },
        { value: "emmc", label: "eMMC" },
      ],
    },
    {
      key: "screen-size-inch",
      label: "حجم الشاشة",
      type: "number",
      group: "display",
      visibleWhen: laptopOnly,
      helpText: "بالبوصة.",
    },
    {
      key: "screen-resolution",
      label: "دقة الشاشة",
      type: "text",
      group: "display",
      visibleWhen: laptopOnly,
      placeholder: "1920×1080 / 2560×1600...",
    },
    {
      key: "screen-panel",
      label: "نوع الشاشة",
      type: "text",
      group: "display",
      visibleWhen: laptopOnly,
      placeholder: "OLED / IPS / Mini LED...",
    },
    {
      key: "refresh-rate-hz",
      label: "معدل التحديث",
      type: "number",
      group: "display",
      visibleWhen: laptopOnly,
      helpText: "Hz",
    },
    {
      key: "battery-wh",
      label: "سعة البطارية",
      type: "number",
      group: "power",
      visibleWhen: laptopOnly,
      helpText: "Wh",
    },
    {
      key: "charger-watt",
      label: "قدرة الشاحن",
      type: "number",
      group: "power",
      visibleWhen: laptopOnly,
      helpText: "W",
    },
    {
      key: "operating-system",
      label: "نظام التشغيل",
      type: "text",
      group: "details",
      visibleWhen: laptopOnly,
      placeholder: "Windows 11 / macOS...",
    },
    {
      key: "wifi",
      label: "Wi-Fi",
      type: "text",
      group: "connectivity",
      visibleWhen: laptopOnly,
      placeholder: "Wi-Fi 6E / Wi-Fi 7",
    },
    {
      key: "bluetooth",
      label: "Bluetooth",
      type: "text",
      group: "connectivity",
      visibleWhen: laptopOnly,
      placeholder: "5.3",
    },
    {
      key: "ports",
      label: "المنافذ",
      type: "textarea",
      group: "connectivity",
      visibleWhen: laptopOnly,
      placeholder: "USB-C، Thunderbolt، HDMI، USB-A...",
    },
    {
      key: "backlit-keyboard",
      label: "كيبورد بإضاءة",
      type: "select",
      group: "details",
      visibleWhen: laptopOnly,
      options: yesNoOptions,
    },
    {
      key: "weight-kg",
      label: "الوزن",
      type: "number",
      group: "details",
      visibleWhen: laptopOnly,
      helpText: "بالكيلوجرام.",
    },
    {
      key: "accessory-type",
      label: "نوع الإكسسوار",
      type: "select",
      group: "identity",
      visibleWhen: accessoryOnly,
      options: [
        { value: "headphones", label: "سماعة رأس" },
        { value: "earbuds", label: "سماعات أذن" },
        { value: "charger", label: "شاحن" },
        { value: "cable", label: "كيبل" },
        { value: "power-bank", label: "باور بانك" },
        { value: "case", label: "غطاء / حماية" },
        { value: "mouse", label: "ماوس" },
        { value: "keyboard", label: "كيبورد" },
        { value: "hub", label: "Hub / محول" },
        { value: "stand", label: "ستاند" },
        { value: "other", label: "أخرى" },
      ],
    },
    {
      key: "compatibility",
      label: "الأجهزة المتوافقة",
      type: "textarea",
      group: "compatibility",
      visibleWhen: accessoryOnly,
      placeholder: "مثال: iPhone 15–17 / USB-C devices...",
    },
    {
      key: "connection-type",
      label: "نوع الاتصال",
      type: "select",
      group: "connectivity",
      visibleWhen: accessoryOnly,
      options: [
        { value: "bluetooth", label: "Bluetooth" },
        { value: "usb-c", label: "USB-C" },
        { value: "usb-a", label: "USB-A" },
        { value: "lightning", label: "Lightning" },
        { value: "3.5mm", label: "3.5mm" },
        { value: "wireless", label: "Wireless" },
        { value: "other", label: "أخرى" },
      ],
    },
    {
      key: "wireless",
      label: "لاسلكي",
      type: "select",
      group: "connectivity",
      visibleWhen: accessoryOnly,
      options: yesNoOptions,
    },
    {
      key: "battery-mah",
      label: "سعة البطارية",
      type: "number",
      group: "power",
      visibleWhen: accessoryOnly,
      helpText: "إن وجدت — mAh",
    },
    {
      key: "battery-life-hours",
      label: "مدة التشغيل",
      type: "number",
      group: "power",
      visibleWhen: accessoryOnly,
      helpText: "بالساعات.",
    },
    {
      key: "power-watt",
      label: "القدرة",
      type: "number",
      group: "power",
      visibleWhen: accessoryOnly,
      helpText: "W",
    },
    {
      key: "cable-length-meter",
      label: "طول الكابل",
      type: "number",
      group: "details",
      visibleWhen: accessoryOnly,
      helpText: "بالمتر.",
    },
    {
      key: "material",
      label: "الخامة",
      type: "text",
      group: "material",
      visibleWhen: accessoryOnly,
    },
    {
      key: "color",
      label: "اللون",
      type: "text",
      group: "design",
      visibleWhen: accessoryOnly,
    },
    {
      key: "size",
      label: "المقاس / الأبعاد",
      type: "text",
      group: "details",
      visibleWhen: accessoryOnly,
    },
    {
      key: "warranty-months",
      label: "مدة الضمان",
      type: "number",
      group: "warranty",
      helpText: "بالأشهر.",
    },
    {
      key: "warranty-provider",
      label: "جهة الضمان",
      type: "text",
      group: "warranty",
      placeholder: "الوكيل / المتجر / الشركة المصنعة",
    },
  ],

  variantDimensions: [
    {
      key: "color",
      label: "اللون",
      placeholder: "أسود / فضي / أبيض...",
    },
    {
      key: "ram",
      label: "RAM / الإصدار",
      placeholder: "8 / 16 / 32 GB أو إصدار المنتج",
    },
    {
      key: "storage",
      label: "السعة / المقاس",
      placeholder: "256 / 512 GB أو المقاس",
    },
  ],
};