// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OFOQ.Market.Infrastructure.Persistence;

#nullable disable

namespace OFOQ.Market.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MarketDbContext))]
    [Migration("20260907221946_AddPaymentProviderAccountsAndWallets")]
    partial class AddPaymentProviderAccountsAndWallets
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OFOQ.Market.Domain.Catalog.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<Guid?>("DeletedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by_user_id");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsVisible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_visible");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentCategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_category_id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("slug");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ak_catalog_categories_tenant_id_id");

                    b.HasIndex("ParentCategoryId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_catalog_categories_tenant_id");

                    b.HasIndex("TenantId", "Slug")
                        .IsUnique()
                        .HasDatabaseName("ux_catalog_categories_tenant_slug_active")
                        .HasFilter("is_deleted = false");

                    b.HasIndex("TenantId", "ParentCategoryId", "SortOrder")
                        .HasDatabaseName("ix_catalog_categories_tenant_parent_sort");

                    b.ToTable("catalog_categories", (string)null);
                });

            modelBuilder.Entity("OFOQ.Market.Domain.Catalog.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<Guid?>("DeletedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by_user_id");

                    b.Property<string>("Description")
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsVisible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_visible");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("slug");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.Property<decimal?>("_compareAtPriceAmount")
                        .HasPrecision(20, 4)
                        .HasColumnType("numeric(20,4)")
                        .HasColumnName("compare_at_price_amount");

                    b.Property<string>("_currencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency_code");

                    b.Property<decimal>("_priceAmount")
                        .HasPrecision(20, 4)
                        .HasColumnType("numeric(20,4)")
                        .HasColumnName("price_amount");

                    b.HasKey("Id");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ak_catalog_products_tenant_id_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_catalog_products_tenant_id");

                    b.HasIndex("TenantId", "CategoryId")
                        .HasDatabaseName("ix_catalog_products_tenant_category");

                    b.HasIndex("TenantId", "Slug")
                        .IsUnique()
                        .HasDatabaseName("ux_catalog_products_tenant_slug_active")
                        .HasFilter("is_deleted = false");

                    b.ToTable("catalog_products", (string)null);
                });

            modelBuilder.Entity("OFOQ.Market.Domain.Catalog.ProductOption", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<Guid?>("DeletedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by_user_id");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("normalized_name");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id");

                    b.HasAlternateKey("TenantId", "ProductId", "Id")
                        .HasName("ak_catalog_product_options_tenant_product_id");

                    b.HasIndex("TenantId", "ProductId", "NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ux_catalog_product_options_product_name_active")
                        .HasFilter("is_deleted = false");

                    b.HasIndex("TenantId", "ProductId", "SortOrder")
                        .HasDatabaseName("ix_catalog_product_options_product_sort");

                    b.ToTable("catalog_product_options", (string)null);
                });

            modelBuilder.Entity("OFOQ.Market.Domain.Catalog.ProductOptionValue", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<Guid?>("DeletedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by_user_id");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("NormalizedValue")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("normalized_value");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<Guid>("ProductOptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_option_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasAlternateKey("TenantId", "ProductId", "ProductOptionId", "Id")
                        .HasName("ak_catalog_product_option_values_scope_id");

                    b.HasIndex("TenantId", "ProductOptionId", "SortOrder")
                        .HasDatabaseName("ix_catalog_product_option_values_option_sort");

                    b.HasIndex("TenantId", "ProductId", "ProductOptionId", "NormalizedValue")
                        .IsUnique()
                        .HasDatabaseName("ux_catalog_product_option_values_option_value_active")
                        .HasFilter("is_deleted = false");

                    b.ToTable("catalog_product_option_values", (string)null);
                });

            modelBuilder.Entity("OFOQ.Market.Domain.Catalog.ProductVariant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<Guid?>("DeletedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by_user_id");

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_default");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_enabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.Property<bool>("_continueSellingWhenOutOfStock")
                        .HasColumnType("boolean")
                        .HasColumnName("continue_selling_when_out_of_stock");

                    b.Property<int>("_lowStockThreshold")
                        .HasColumnType("integer")
                        .HasColumnName("low_stock_threshold");

                    b.Property<decimal?>("_priceOverrideAmount")
                        .HasPrecision(20, 4)
                        .HasColumnType("numeric(20,4)")
                        .HasColumnName("price_override_amount");

                    b.Property<string>("_priceOverrideCurrencyCode")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("price_override_currency_code");

                    b.Property<int>("_quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<string>("_skuValue")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sku");

                    b.Property<bool>("_trackInventory")
                        .HasColumnType("boolean")
                        .HasColumnName("track_inventory");

                    b.HasKey("Id");

                    b.HasAlternateKey("TenantId", "ProductId", "Id")
                        .HasName("ak_catalog_product_variants_tenant_product_id");

                    b.HasIndex("TenantId", "ProductId")
                        .IsUnique()
                        .HasDatabaseName("ux_catalog_product_variants_default_per_product")
                        .HasFilter("is_default = true AND is_deleted = false");

                    b.HasIndex("TenantId", "_skuValue")
                        .IsUnique()
                        .HasDatabaseName("ux_catalog_product_variants_tenant_sku_active")
                        .HasFilter("is_deleted = false");

                    b.ToTable("catalog_product_variants", (string)null);
                });

            modelBuilder.Entity("OFOQ.Market.Domain.Catalog.ProductVariantOptionValue", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<Guid?>("DeletedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by_user_id");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<Guid>("ProductOptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_option_id");

                    b.Property<Guid>("ProductOptionValueId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_option_value_id");

                    b.Property<Guid>("ProductVariantId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_variant_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ProductId", "ProductVariantId")
                        .HasDatabaseName("ix_catalog_variant_option_values_variant");

                    b.HasIndex("TenantId", "ProductId", "ProductOptionId", "ProductOptionValueId");

                    b.HasIndex("TenantId", "ProductId", "ProductVariantId", "ProductOptionId")
                        .IsUnique()
                        .HasDatabaseName("ux_catalog_variant_option_single_value_active")
                        .HasFilter("is_deleted = false");

                    b.ToTable("catalog_product_variant_option_values", (string)null);
                });

            modelBuilder.Entity("OFOQ.Market.Domain.Commerce.Carts.Cart", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.Property<string>("_currencyCode")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency_code");

                    b.Property<Guid?>("_customerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_user_id");

                    b.HasKey("Id");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ak_commerce_carts_tenant_id_id");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_commerce_carts_tenant_status");

                    b.HasIndex("TenantId", "_customerUserId")
                        .IsUnique()
                        .HasDatabaseName("ux_commerce_carts_active_customer")
                        .HasFilter("status = 0 AND customer_user_id IS NOT NULL");

                    b.ToTable("commerce_carts", (string)null);
                });

            modelBuilder.Entity("OFOQ.Market.Domain.Commerce.Carts.CartItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CartId")
                        .HasColumnType("uuid")
                        .HasColumnName("cart_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<Guid>("ProductVariantId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_variant_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.Property<decimal>("_unitPriceAmount")
                        .HasPrecision(20, 4)
                        .HasColumnType("numeric(20,4)")
                        .HasColumnName("unit_price_amount");

                    b.Property<string>("_unitPriceCurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("unit_price_currency_code");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "CartId")
                        .HasDatabaseName("ix_commerce_cart_items_cart");

                    b.HasIndex("TenantId", "CartId", "ProductVariantId")
                        .IsUnique()
                        .HasDatabaseName("ux_commerce_cart_items_cart_variant");

                    b.HasIndex("TenantId", "ProductId", "ProductVariantId");

                    b.ToTable("commerce_cart_items", null, t =>
                        {
                            t.HasCheckConstraint("ck_commerce_cart_items_price_nonnegative", "unit_price_amount >= 0");

                            t.HasCheckConstraint("ck_commerce_cart_items_quantity", "quantity > 0 AND quantity <= 999");
                        });
                });

            modelBuilder.Entity("OFOQ.Market.Domain.Commerce.Orders.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CheckoutIdempotencyKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("checkout_idempotency_key");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.Property<string>("_currencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency_code");

                    b.Property<Guid>("_customerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_user_id");

                    b.Property<Guid>("_sourceCartId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_cart_id");

                    b.HasKey("Id");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ak_commerce_orders_tenant_id_id");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_commerce_orders_tenant_status");

                    b.HasIndex("TenantId", "_sourceCartId")
                        .IsUnique()
                        .HasDatabaseName("ux_commerce_orders_tenant_source_cart");

                    b.HasIndex("TenantId", "_customerUserId", "CheckoutIdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ux_commerce_orders_checkout_idempotency")
                        .HasFilter("checkout_idempotency_key IS NOT NULL");

                    b.HasIndex("TenantId", "_customerUserId", "CreatedAtUtc")
                        .HasDatabaseName("ix_commerce_orders_tenant_customer_created");

                    b.ToTable("commerce_orders", (string)null);
                });

            modelBuilder.Entity("OFOQ.Market.Domain.Commerce.Orders.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("product_name");

                    b.Property<Guid>("ProductVariantId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_variant_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sku");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("VariantName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("variant_name");

                    b.Property<decimal>("_unitPriceAmount")
                        .HasPrecision(20, 4)
                        .HasColumnType("numeric(20,4)")
                        .HasColumnName("unit_price_amount");

                    b.Property<string>("_unitPriceCurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("unit_price_currency_code");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "OrderId")
                        .HasDatabaseName("ix_commerce_order_items_order");

                    b.HasIndex("TenantId", "OrderId", "ProductVariantId")
                        .IsUnique()
                        .HasDatabaseName("ux_commerce_order_items_order_variant");

                    b.HasIndex("TenantId", "ProductId", "ProductVariantId")
                        .HasDatabaseName("ix_commerce_order_items_product_variant");

                    b.ToTable("commerce_order_items", null, t =>
                        {
                            t.HasCheckConstraint("ck_commerce_order_items_price_nonnegative", "unit_price_amount >= 0");

                            t.HasCheckConstraint("ck_commerce_order_items_quantity", "quantity > 0 AND quantity <= 999");
                        });
                });

            modelBuilder.Entity("OFOQ.Market.Domain.Commerce.Payments.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.Property<string>("_currencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency_code");

                    b.Property<Guid>("_customerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_user_id");

                    b.HasKey("Id");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ak_commerce_payments_tenant_id_id");

                    b.HasIndex("TenantId", "OrderId")
                        .IsUnique()
                        .HasDatabaseName("ux_commerce_payments_tenant_order");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_commerce_payments_tenant_status");

                    b.HasIndex("TenantId", "_customerUserId", "CreatedAtUtc")
                        .HasDatabaseName("ix_commerce_payments_tenant_customer_created");

                    b.ToTable("commerce_payments", null, t =>
                        {
                            t.HasCheckConstraint("ck_commerce_payments_amount_positive", "amount > 0");
                        });
                });

            modelBuilder.Entity("OFOQ.Market.Domain.Commerce.Payments.PaymentIntent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("ActionType")
                        .HasColumnType("integer");

                    b.Property<string>("ActionValue")
                        .HasColumnType("text");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("amount");

                    b.Property<string>("CreateIdempotencyKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("create_idempotency_key");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<int>("MethodType")
                        .HasColumnType("integer")
                        .HasColumnName("method_type");

                    b.Property<Guid>("PaymentId")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_id");

                    b.Property<string>("ProviderReference")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("provider_reference");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("TenantPaymentMethodId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_payment_method_id");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.Property<string>("_currencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency_code");

                    b.Property<Guid>("_customerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_user_id");

                    b.Property<string>("_providerCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("provider_code");

                    b.HasKey("Id");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ak_commerce_payment_intents_tenant_id_id");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_commerce_payment_intents_tenant_status");

                    b.HasIndex("TenantId", "PaymentId", "CreatedAtUtc")
                        .HasDatabaseName("ix_commerce_payment_intents_payment_created");

                    b.HasIndex("TenantId", "TenantPaymentMethodId", "ProviderReference")
                        .IsUnique()
                        .HasDatabaseName("ux_commerce_payment_intents_method_provider_reference")
                        .HasFilter("provider_reference IS NOT NULL");

                    b.HasIndex("TenantId", "_customerUserId", "CreateIdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ux_commerce_payment_intents_create_idempotency")
                        .HasFilter("create_idempotency_key IS NOT NULL");

                    b.ToTable("commerce_payment_intents", null, t =>
                        {
                            t.HasCheckConstraint("ck_commerce_payment_intents_amount_positive", "amount > 0");
                        });
                });

            modelBuilder.Entity("OFOQ.Market.Domain.Commerce.Payments.PaymentTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("ExternalEventId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("external_event_id");

                    b.Property<Guid>("PaymentIntentId")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_intent_id");

                    b.Property<string>("ProviderReference")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("provider_reference");

                    b.Property<int>("ResultingStatus")
                        .HasColumnType("integer")
                        .HasColumnName("resulting_status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<string>("_currencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency_code");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "PaymentIntentId", "CreatedAtUtc")
                        .HasDatabaseName("ix_commerce_payment_transactions_intent_created");

                    b.HasIndex("TenantId", "PaymentIntentId", "ExternalEventId")
                        .IsUnique()
                        .HasDatabaseName("ux_commerce_payment_transactions_external_event")
                        .HasFilter("external_event_id IS NOT NULL");

                    b.ToTable("commerce_payment_transactions", null, t =>
                        {
                            t.HasCheckConstraint("ck_commerce_payment_transactions_amount_positive", "amount > 0");
                        });
                });

            modelBuilder.Entity("OFOQ.Market.Domain.Commerce.Payments.TenantPaymentCapability", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<int>("ElectronicPaymentsStatus")
                        .HasColumnType("integer")
                        .HasColumnName("electronic_payments_status");

                    b.Property<DateTimeOffset?>("SuspendedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("suspended_at_utc");

                    b.Property<Guid?>("SuspendedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("suspended_by_user_id");

                    b.Property<string>("SuspensionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("suspension_reason");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .IsUnique()
                        .HasDatabaseName("ux_commerce_tenant_payment_capabilities_tenant");

                    b.ToTable("commerce_tenant_payment_capabilities", (string)null);
                });

            modelBuilder.Entity("OFOQ.Market.Domain.Commerce.Payments.TenantPaymentMethod", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<decimal?>("MaximumAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("maximum_amount");

                    b.Property<decimal?>("MinimumAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("minimum_amount");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("method_type");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.Property<string>("_countryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("country_code");

                    b.Property<string>("_currencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency_code");

                    b.Property<string>("_providerCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("provider_code");

                    b.HasKey("Id");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ak_commerce_tenant_payment_methods_tenant_id_id");

                    b.HasIndex("TenantId", "IsEnabled")
                        .HasDatabaseName("ix_commerce_tenant_payment_methods_tenant_enabled");

                    b.HasIndex("TenantId", "_providerCode", "_currencyCode")
                        .HasDatabaseName("ix_commerce_tenant_payment_methods_provider_currency");

                    b.ToTable("commerce_tenant_payment_methods", null, t =>
                        {
                            t.HasCheckConstraint("ck_commerce_tenant_payment_methods_limits_order", "minimum_amount IS NULL OR maximum_amount IS NULL OR minimum_amount <= maximum_amount");

                            t.HasCheckConstraint("ck_commerce_tenant_payment_methods_maximum_nonnegative", "maximum_amount IS NULL OR maximum_amount >= 0");

                            t.HasCheckConstraint("ck_commerce_tenant_payment_methods_minimum_nonnegative", "minimum_amount IS NULL OR minimum_amount >= 0");
                        });
                });

            modelBuilder.Entity("OFOQ.Market.Domain.Commerce.Payments.TenantPaymentProviderAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<int>("CredentialsVersion")
                        .HasColumnType("integer")
                        .HasColumnName("credentials_version");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<int>("Environment")
                        .HasColumnType("integer")
                        .HasColumnName("environment");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<string>("ProtectedCredentials")
                        .HasColumnType("text")
                        .HasColumnName("protected_credentials");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.Property<string>("_providerCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("provider_code");

                    b.HasKey("Id");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ak_commerce_tenant_payment_provider_accounts_tenant_id_id");

                    b.HasIndex("TenantId", "_providerCode")
                        .IsUnique()
                        .HasDatabaseName("ux_commerce_pay_provider_accounts_tenant_provider_enabled")
                        .HasFilter("is_enabled = TRUE");

                    b.HasIndex("TenantId", "_providerCode", "Environment")
                        .IsUnique()
                        .HasDatabaseName("ux_commerce_pay_provider_accounts_tenant_provider_env");

                    b.ToTable("commerce_tenant_payment_provider_accounts", (string)null);
                });

            modelBuilder.Entity("OFOQ.Market.Domain.Commerce.Payments.TenantPaymentWalletCapability", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<Guid>("ProviderAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("provider_account_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.Property<int>("WalletType")
                        .HasColumnType("integer")
                        .HasColumnName("wallet_type");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ProviderAccountId", "WalletType")
                        .IsUnique()
                        .HasDatabaseName("ux_commerce_pay_wallet_caps_tenant_account_wallet");

                    b.ToTable("commerce_tenant_payment_wallet_capabilities", (string)null);
                });

            modelBuilder.Entity("OFOQ.Market.Domain.Identity.MfaLoginChallenge", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ConsumedAtUtc")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at_utc");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<int>("FailedAttemptCount")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("failed_attempt_count");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at_utc");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token_hash");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_mfa_login_challenges_token_hash");

                    b.HasIndex("UserId", "ExpiresAtUtc")
                        .HasDatabaseName("ix_mfa_login_challenges_user_expires");

                    b.ToTable("mfa_login_challenges", (string)null);
                });

            modelBuilder.Entity("OFOQ.Market.Domain.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<Guid?>("DeletedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by_user_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset?>("EmailVerifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("email_verified_at_utc");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ux_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("OFOQ.Market.Domain.Identity.UserMfa", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTimeOffset?>("EnabledAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enabled_at_utc");

                    b.Property<long?>("LastAcceptedTimeStep")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("last_accepted_time_step");

                    b.Property<string>("ProtectedSecret")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)")
                        .HasColumnName("protected_secret");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ux_user_mfa_user_id");

                    b.ToTable("user_mfa", (string)null);
                });

            modelBuilder.Entity("OFOQ.Market.Domain.Identity.UserMfaRecoveryCode", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("code_hash");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.Property<DateTimeOffset?>("UsedAtUtc")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at_utc");

                    b.Property<Guid>("UserMfaId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_mfa_id");

                    b.HasKey("Id");

                    b.HasIndex("UserMfaId")
                        .HasDatabaseName("ix_user_mfa_recovery_codes_user_mfa_id");

                    b.HasIndex("UserMfaId", "CodeHash")
                        .IsUnique()
                        .HasDatabaseName("ux_user_mfa_recovery_codes_mfa_hash");

                    b.ToTable("user_mfa_recovery_codes", (string)null);
                });

            modelBuilder.Entity("OFOQ.Market.Domain.Tenancy.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<Guid?>("DeletedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by_user_id");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("character varying(63)")
                        .HasColumnName("slug");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ux_tenants_slug");

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("OFOQ.Market.Domain.Tenancy.TenantDomain", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<Guid?>("DeletedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by_user_id");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(253)
                        .HasColumnType("character varying(253)")
                        .HasColumnName("domain");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsPrimary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_primary");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.Property<DateTimeOffset?>("VerifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verified_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("Domain")
                        .IsUnique()
                        .HasDatabaseName("ux_tenant_domains_domain");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_tenant_domains_tenant_id");

                    b.HasIndex("TenantId", "IsPrimary")
                        .IsUnique()
                        .HasDatabaseName("ux_tenant_domains_one_primary_per_tenant")
                        .HasFilter("\"is_primary\" = TRUE AND \"is_deleted\" = FALSE");

                    b.ToTable("tenant_domains", (string)null);
                });

            modelBuilder.Entity("OFOQ.Market.Domain.Tenancy.TenantMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<Guid?>("DeletedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by_user_id");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("role");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_tenant_memberships_user_id");

                    b.HasIndex("TenantId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ux_tenant_memberships_tenant_user");

                    b.ToTable("tenant_memberships", (string)null);
                });

            modelBuilder.Entity("OFOQ.Market.Domain.Catalog.Category", b =>
                {
                    b.HasOne("OFOQ.Market.Domain.Catalog.Category", null)
                        .WithMany()
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_catalog_categories_parent_category_id");

                    b.HasOne("OFOQ.Market.Domain.Tenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_catalog_categories_tenants_tenant_id");
                });

            modelBuilder.Entity("OFOQ.Market.Domain.Catalog.Product", b =>
                {
                    b.HasOne("OFOQ.Market.Domain.Tenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_catalog_products_tenants_tenant_id");

                    b.HasOne("OFOQ.Market.Domain.Catalog.Category", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CategoryId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_catalog_products_categories_tenant_category");
                });

            modelBuilder.Entity("OFOQ.Market.Domain.Catalog.ProductOption", b =>
                {
                    b.HasOne("OFOQ.Market.Domain.Tenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_catalog_product_options_tenants");

                    b.HasOne("OFOQ.Market.Domain.Catalog.Product", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ProductId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_catalog_product_options_products");
                });

            modelBuilder.Entity("OFOQ.Market.Domain.Catalog.ProductOptionValue", b =>
                {
                    b.HasOne("OFOQ.Market.Domain.Tenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_catalog_product_option_values_tenants");

                    b.HasOne("OFOQ.Market.Domain.Catalog.Product", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ProductId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_catalog_product_option_values_products");

                    b.HasOne("OFOQ.Market.Domain.Catalog.ProductOption", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ProductId", "ProductOptionId")
                        .HasPrincipalKey("TenantId", "ProductId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_catalog_product_option_values_options");
                });

            modelBuilder.Entity("OFOQ.Market.Domain.Catalog.ProductVariant", b =>
                {
                    b.HasOne("OFOQ.Market.Domain.Tenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_catalog_product_variants_tenants_tenant_id");

                    b.HasOne("OFOQ.Market.Domain.Catalog.Product", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ProductId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_catalog_product_variants_products_tenant_product");
                });

            modelBuilder.Entity("OFOQ.Market.Domain.Catalog.ProductVariantOptionValue", b =>
                {
                    b.HasOne("OFOQ.Market.Domain.Tenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_catalog_variant_option_values_tenants");

                    b.HasOne("OFOQ.Market.Domain.Catalog.Product", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ProductId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_catalog_variant_option_values_products");

                    b.HasOne("OFOQ.Market.Domain.Catalog.ProductOption", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ProductId", "ProductOptionId")
                        .HasPrincipalKey("TenantId", "ProductId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_catalog_variant_option_values_options");

                    b.HasOne("OFOQ.Market.Domain.Catalog.ProductVariant", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ProductId", "ProductVariantId")
                        .HasPrincipalKey("TenantId", "ProductId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_catalog_variant_option_values_variants");

                    b.HasOne("OFOQ.Market.Domain.Catalog.ProductOptionValue", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ProductId", "ProductOptionId", "ProductOptionValueId")
                        .HasPrincipalKey("TenantId", "ProductId", "ProductOptionId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_catalog_variant_option_values_values");
                });

            modelBuilder.Entity("OFOQ.Market.Domain.Commerce.Carts.Cart", b =>
                {
                    b.HasOne("OFOQ.Market.Domain.Tenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_commerce_carts_tenants");
                });

            modelBuilder.Entity("OFOQ.Market.Domain.Commerce.Carts.CartItem", b =>
                {
                    b.HasOne("OFOQ.Market.Domain.Tenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_commerce_cart_items_tenants");

                    b.HasOne("OFOQ.Market.Domain.Commerce.Carts.Cart", null)
                        .WithMany("_items")
                        .HasForeignKey("TenantId", "CartId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_commerce_cart_items_carts");

                    b.HasOne("OFOQ.Market.Domain.Catalog.Product", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ProductId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_commerce_cart_items_products");

                    b.HasOne("OFOQ.Market.Domain.Catalog.ProductVariant", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ProductId", "ProductVariantId")
                        .HasPrincipalKey("TenantId", "ProductId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_commerce_cart_items_variants");
                });

            modelBuilder.Entity("OFOQ.Market.Domain.Commerce.Orders.Order", b =>
                {
                    b.HasOne("OFOQ.Market.Domain.Tenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_commerce_orders_tenants");

                    b.HasOne("OFOQ.Market.Domain.Commerce.Carts.Cart", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "_sourceCartId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_commerce_orders_source_cart");
                });

            modelBuilder.Entity("OFOQ.Market.Domain.Commerce.Orders.OrderItem", b =>
                {
                    b.HasOne("OFOQ.Market.Domain.Tenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_commerce_order_items_tenants");

                    b.HasOne("OFOQ.Market.Domain.Commerce.Orders.Order", null)
                        .WithMany("_items")
                        .HasForeignKey("TenantId", "OrderId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_commerce_order_items_orders");

                    b.HasOne("OFOQ.Market.Domain.Catalog.Product", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ProductId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_commerce_order_items_products");

                    b.HasOne("OFOQ.Market.Domain.Catalog.ProductVariant", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ProductId", "ProductVariantId")
                        .HasPrincipalKey("TenantId", "ProductId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_commerce_order_items_variants");
                });

            modelBuilder.Entity("OFOQ.Market.Domain.Commerce.Payments.Payment", b =>
                {
                    b.HasOne("OFOQ.Market.Domain.Tenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_commerce_payments_tenants");

                    b.HasOne("OFOQ.Market.Domain.Commerce.Orders.Order", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "OrderId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_commerce_payments_orders");
                });

            modelBuilder.Entity("OFOQ.Market.Domain.Commerce.Payments.PaymentIntent", b =>
                {
                    b.HasOne("OFOQ.Market.Domain.Tenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_commerce_payment_intents_tenants");

                    b.HasOne("OFOQ.Market.Domain.Commerce.Payments.Payment", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "PaymentId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_commerce_payment_intents_payments");

                    b.HasOne("OFOQ.Market.Domain.Commerce.Payments.TenantPaymentMethod", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "TenantPaymentMethodId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_commerce_payment_intents_tenant_payment_methods");
                });

            modelBuilder.Entity("OFOQ.Market.Domain.Commerce.Payments.PaymentTransaction", b =>
                {
                    b.HasOne("OFOQ.Market.Domain.Commerce.Payments.PaymentIntent", null)
                        .WithMany("_transactions")
                        .HasForeignKey("TenantId", "PaymentIntentId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_commerce_payment_transactions_intents");
                });

            modelBuilder.Entity("OFOQ.Market.Domain.Commerce.Payments.TenantPaymentCapability", b =>
                {
                    b.HasOne("OFOQ.Market.Domain.Tenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_commerce_tenant_payment_capabilities_tenants");
                });

            modelBuilder.Entity("OFOQ.Market.Domain.Commerce.Payments.TenantPaymentMethod", b =>
                {
                    b.HasOne("OFOQ.Market.Domain.Tenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_commerce_tenant_payment_methods_tenants");
                });

            modelBuilder.Entity("OFOQ.Market.Domain.Commerce.Payments.TenantPaymentProviderAccount", b =>
                {
                    b.HasOne("OFOQ.Market.Domain.Tenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_commerce_tenant_payment_provider_accounts_tenants");
                });

            modelBuilder.Entity("OFOQ.Market.Domain.Commerce.Payments.TenantPaymentWalletCapability", b =>
                {
                    b.HasOne("OFOQ.Market.Domain.Tenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_commerce_tenant_payment_wallet_capabilities_tenants");

                    b.HasOne("OFOQ.Market.Domain.Commerce.Payments.TenantPaymentProviderAccount", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ProviderAccountId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_commerce_pay_wallet_caps_provider_accounts");
                });

            modelBuilder.Entity("OFOQ.Market.Domain.Identity.MfaLoginChallenge", b =>
                {
                    b.HasOne("OFOQ.Market.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_mfa_login_challenges_users_user_id");
                });

            modelBuilder.Entity("OFOQ.Market.Domain.Identity.UserMfa", b =>
                {
                    b.HasOne("OFOQ.Market.Domain.Identity.User", null)
                        .WithOne()
                        .HasForeignKey("OFOQ.Market.Domain.Identity.UserMfa", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_mfa_users_user_id");
                });

            modelBuilder.Entity("OFOQ.Market.Domain.Identity.UserMfaRecoveryCode", b =>
                {
                    b.HasOne("OFOQ.Market.Domain.Identity.UserMfa", null)
                        .WithMany()
                        .HasForeignKey("UserMfaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_mfa_recovery_codes_user_mfa_id");
                });

            modelBuilder.Entity("OFOQ.Market.Domain.Tenancy.TenantDomain", b =>
                {
                    b.HasOne("OFOQ.Market.Domain.Tenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tenant_domains_tenants_tenant_id");
                });

            modelBuilder.Entity("OFOQ.Market.Domain.Tenancy.TenantMembership", b =>
                {
                    b.HasOne("OFOQ.Market.Domain.Tenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tenant_memberships_tenants_tenant_id");

                    b.HasOne("OFOQ.Market.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tenant_memberships_users_user_id");
                });

            modelBuilder.Entity("OFOQ.Market.Domain.Commerce.Carts.Cart", b =>
                {
                    b.Navigation("_items");
                });

            modelBuilder.Entity("OFOQ.Market.Domain.Commerce.Orders.Order", b =>
                {
                    b.Navigation("_items");
                });

            modelBuilder.Entity("OFOQ.Market.Domain.Commerce.Payments.PaymentIntent", b =>
                {
                    b.Navigation("_transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
